/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as ThesisRouteImport } from './routes/thesis'
import { Route as FoundersIdRouteImport } from './routes/founders.$id'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as OpportunitiesIdMemoRouteImport } from './routes/opportunities_.$id.memo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesisRoute = ThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersIdRoute = FoundersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FoundersRoute,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdMemoRoute = OpportunitiesIdMemoRouteImport.update({
  id: '/opportunities_/$id/memo',
  path: '/opportunities/$id/memo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/founders': typeof FoundersRouteWithChildren
  '/thesis': typeof ThesisRoute
  '/founders/$id': typeof FoundersIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/$id/memo': typeof OpportunitiesIdMemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/founders': typeof FoundersRouteWithChildren
  '/thesis': typeof ThesisRoute
  '/founders/$id': typeof FoundersIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/$id/memo': typeof OpportunitiesIdMemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/founders': typeof FoundersRouteWithChildren
  '/thesis': typeof ThesisRoute
  '/founders/$id': typeof FoundersIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities_/$id/memo': typeof OpportunitiesIdMemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/founders'
    | '/thesis'
    | '/founders/$id'
    | '/opportunities/$id'
    | '/opportunities/$id/memo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/founders'
    | '/thesis'
    | '/founders/$id'
    | '/opportunities/$id'
    | '/opportunities/$id/memo'
  id:
    | '__root__'
    | '/'
    | '/founders'
    | '/thesis'
    | '/founders/$id'
    | '/opportunities/$id'
    | '/opportunities_/$id/memo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoundersRoute: typeof FoundersRouteWithChildren
  ThesisRoute: typeof ThesisRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesIdMemoRoute: typeof OpportunitiesIdMemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thesis': {
      id: '/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof ThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders/$id': {
      id: '/founders/$id'
      path: '/$id'
      fullPath: '/founders/$id'
      preLoaderRoute: typeof FoundersIdRouteImport
      parentRoute: typeof FoundersRoute
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities_/$id/memo': {
      id: '/opportunities_/$id/memo'
      path: '/opportunities/$id/memo'
      fullPath: '/opportunities/$id/memo'
      preLoaderRoute: typeof OpportunitiesIdMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FoundersRouteChildren {
  FoundersIdRoute: typeof FoundersIdRoute
}

const FoundersRouteChildren: FoundersRouteChildren = {
  FoundersIdRoute: FoundersIdRoute,
}

const FoundersRouteWithChildren = FoundersRoute._addFileChildren(
  FoundersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoundersRoute: FoundersRouteWithChildren,
  ThesisRoute: ThesisRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesIdMemoRoute: OpportunitiesIdMemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
